
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paymentrequest.proto

package org.bitcoin.protocols.payments;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:payments.Output)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 amount = 1 [default = 0];</code>
     *
     * <pre>
     * amount is integer-number-of-satoshis
     * </pre>
     */
    boolean hasAmount();
    /**
     * <code>optional uint64 amount = 1 [default = 0];</code>
     *
     * <pre>
     * amount is integer-number-of-satoshis
     * </pre>
     */
    long getAmount();

    /**
     * <code>required bytes script = 2;</code>
     *
     * <pre>
     * usually one of the standard Script forms
     * </pre>
     */
    boolean hasScript();
    /**
     * <code>required bytes script = 2;</code>
     *
     * <pre>
     * usually one of the standard Script forms
     * </pre>
     */
    com.google.protobuf.ByteString getScript();
  }
  /**
   * Protobuf type {@code payments.Output}
   *
   * <pre>
   * Generalized form of "send payment to this/these bitcoin addresses"
   * </pre>
   */
  public static final class Output extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:payments.Output)
      OutputOrBuilder {
    // Use Output.newBuilder() to construct.
    private Output(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Output(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Output defaultInstance;
    public static Output getDefaultInstance() {
      return defaultInstance;
    }

    public Output getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Output(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              amount_ = input.readUInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              script_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoin.protocols.payments.Protos.internal_static_payments_Output_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoin.protocols.payments.Protos.internal_static_payments_Output_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bitcoin.protocols.payments.Protos.Output.class, org.bitcoin.protocols.payments.Protos.Output.Builder.class);
    }

    public static com.google.protobuf.Parser<Output> PARSER =
        new com.google.protobuf.AbstractParser<Output>() {
      public Output parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {